
- name: Disable all to limit channels consumed
  command: subscription-manager repos --disable=\*

- name: Enabled desired channels
  command: subscription-manager repos --enable={{ item }}
  with_items: "{{ repository_channels }}"
