# a standard, basic RHEL server or servers

- name: disable all repositories so we can enable just the ones we want
  command: subscription-manager repos --disable=\*

- name: enable the needed rhel repositories
  command: subscription-manager repos --enable={{ item }}
  with_items: "{{ repo_channels }}"

- name: update all servers
  yum: name=* state=latest

- name: reboot each system
  shell: sleep 2 && systemctl reboot
  async: 1
  poll: 0
  ignore_errors: true

- name: wait for server to come back
  local_action: wait_for host={{ inventory_hostname }} state=started delay=30 timeout=300 port=22
  sudo: false
