employee_sku: 8a85f9863f14fed3013f81ba2b6120b2

repo_channels:
  - rhel-7-server-rpms
  - rhel-server-rhscl-7-rpms
  - rhel-7-server-satellite-6.2-rpms

ssh_known_hosts_file: /root/.ssh/known_hosts

domain: example.org
org: Example
loc: Indianapolis

foreman-admin-password: redhat
foreman-proxy-dns: true
foreman-proxy-dns-interface: eth0
foreman-proxy-dns-zone: $DOMAIN
foreman-proxy-dns-forwarders: 192.168.126.1
foreman-proxy-dns-reverse: 126.168.192.in-addr.arpa
foreman-proxy-dhcp: true
foreman-proxy-dhcp-interface: eth0
foreman-proxy-dhcp-range: "192.168.126.100 192.168.126.150"
foreman-proxy-dhcp-gateway: 192.168.126.1
foreman-proxy-dhcp-nameservers: 192.168.126.2
foreman-proxy-tftp: true
foreman-proxy-tftp-servername: $(hostname)
capsule-puppet: true
foreman-proxy-puppetca: true
foreman-proxy-plugin-remote-execution-ssh-enabled: true
foreman-initial-organization: $ORG \
foreman-initial-location: $LOC

