- hosts: laptop
  vars_files:
  - vault.yml
  vars:
    group: rhel
    # The Red Hat supplied RHEL 7 image
    disk_image: /home/tbowling/Downloads/ISOS/rhel-guest-image-7.2-20160302.0.x86_64.qcow2
  remote_user: root
  become: yes
  become_method: sudo
  become_user: root
  roles:
  - kvm_hypervisor

- hosts: rhel
  vars_files:
    - vault.yml
  remote_user: cloud-user
  become: yes
  become_user: root
  roles:
  - rhel


- hosts: util7vm
  vars_files:
    - vault.yml
  become: yes
  become_method: sudo
  become_user: root
  roles:
  - rhel
